name: .NET CI con SonarCloud

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-analyze:
    runs-on: ubuntu-latest
    env:
      BUILD_CONFIGURATION: Release
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Instalar SonarScanner
        if: ${{ env.SONAR_TOKEN != '' && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository) }}
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Agregar herramientas globales de .NET al PATH
        if: ${{ env.SONAR_TOKEN != '' && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository) }}
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Iniciar análisis de SonarCloud
        if: ${{ env.SONAR_TOKEN != '' && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin \
          /k:"edelapaz_CalculadoraEPN" \
          /o:"edelapaz" \
          /d:sonar.token="$SONAR_TOKEN" \
          /d:sonar.host.url="https://sonarcloud.io" \
          /d:sonar.cs.opencover.reportsPaths="${{ github.workspace }}/coverage.opencover.xml"

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Compilar el proyecto
        run: dotnet build --no-restore --configuration $BUILD_CONFIGURATION

      - name: Ejecutar pruebas y generar cobertura
        run: dotnet test --no-build --configuration $BUILD_CONFIGURATION --collect:"XPlat Code Coverage;Format=opencover" --results-directory ./TestResults

      - name: Rescatar archivo de cobertura
        run: |
          find ./TestResults -name "coverage.opencover.xml" -exec cp {} ${{ github.workspace }}/coverage.opencover.xml \;
          ls -la ${{ github.workspace }}/coverage.opencover.xml

      - name: Finalizar análisis y enviar a SonarCloud
        if: ${{ env.SONAR_TOKEN != '' && (github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository) }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
        run: dotnet sonarscanner end /d:sonar.token="$SONAR_TOKEN"
